try:
    print(a)

except Exception as ex:
    print('에러가 발생 했습니다', ex)
